# Generated by Django 4.2.17 on 2025-01-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_image_product_more_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='more_images',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='products/addtional_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Additional_images', to='product.product')),
            ],
        ),
    ]
